#!/bin/sh
# auto/config - live-build configuration for ZenvX OS
# This script is run by `lb config` and sets all build parameters.
set -e

lb config noauto \
	--mode debian \
	--system live \
	--distribution bookworm \
	--architectures amd64 \
	--linux-flavours amd64 \
	--archive-areas "main contrib non-free non-free-firmware" \
	--mirror-bootstrap "http://deb.debian.org/debian/" \
	--mirror-chroot "http://deb.debian.org/debian/" \
	--mirror-binary "http://deb.debian.org/debian/" \
	--mirror-chroot-security "http://security.debian.org/debian-security" \
	--mirror-binary-security "http://security.debian.org/debian-security" \
	--security true \
	--binary-images iso-hybrid \
	--bootloaders "grub-efi,syslinux" \
	--uefi-secure-boot disable \
	--iso-application "ZenvX OS" \
	--iso-volume "ZENVX-OS" \
	--iso-publisher "ZenvX Project" \
	--image-name "zenvx-os" \
	--debian-installer none \
	--memtest none \
	--win32-loader false \
	--firmware-binary true \
	--firmware-chroot true \
	--apt-indices false \
	--apt-recommends true \
	"${@}"
